# Generated by Django 4.2.4 on 2023-08-13 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('text', models.TextField(default='')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('files', models.FileField(blank=True, null=True, upload_to='files')),
                ('category', models.CharField(choices=[('TK', 'Танки'), ('XL', 'Хилы'), ('DD', 'ДД'), ('TG', 'Торговцы'), ('GM', 'Гилдмастеры'), ('KG', 'Квестгиверы'), ('KU', 'Кузнецы'), ('KG', 'Кожевники'), ('ZE', 'Зельевары'), ('MZ', 'Мастера заклинаний')], max_length=2)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.advertisement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
