# Generated by Django 4.2.4 on 2023-08-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_advertisement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('TK', 'Танки'), ('XL', 'Хилы'), ('DD', 'ДД'), ('TG', 'Торговцы'), ('GM', 'Гилдмастеры'), ('KG', 'Квестгиверы'), ('KU', 'Кузнецы'), ('KG', 'Кожевники'), ('ZE', 'Зельевары'), ('MZ', 'Мастера заклинаний')], default='TK', max_length=2),
        ),
    ]
